export const dummyPlays = [
  {
    id: 1,
    title: "Great Gatsby",
    rating: 9.5,
    tone: "Drama",
    actorCount: 5,
    pages: 38,
    authorName: "Leonardo Dicaprio",
    authorGender: "Male",
    authorEthnicity: "--",
    authorRegion: "Florida",
  },
  {
    id: 2,
    title: "McBeth",
    rating: 9.0,
    tone: "Drama",
    actorCount: 3,
    pages: 12,
    authorName: "Will ShakeASpear",
    authorGender: "Male",
    authorEthnicity: "--",
    authorRegion: "UK",
  },
  {
    id: 3,
    title: "All Dogs go to Heaven",
    rating: 10,
    tone: "Comedy",
    actorCount: 2,
    pages: 14,
    authorName: "Jeff Bezos",
    authorGender: "Male",
    authorEthnicity: "--",
    authorRegion: "Washington",
  },
  {
    id: 4,
    title: "Diary of a Wimpy Kid",
    rating: 9.1,
    tone: "Comedy",
    actorCount: 3,
    pages: 23,
    authorName: "Jeff Kinney",
    authorGender: "Male",
    authorEthnicity: "--",
    authorRegion: "Vermont",
  },
  {
    id: 5,
    title: "Les Miserables",
    rating: 10,
    tone: "Drama",
    actorCount: 5,
    pages: 32,
    authorName: "Minney Mouse",
    authorGender: "Female",
    authorEthnicity: "--",
    authorRegion: "Florida",
  },
  {
    id: 6,
    title: "Hercules",
    rating: 9.4,
    tone: "Comedy",
    actorCount: 3,
    pages: 23,
    authorName: "John Dough",
    authorGender: "Male",
    authorEthnicity: "--",
    authorRegion: "Vermont",
  },
  {
    id: 7,
    title: "Les Miserables 2",
    rating: 9.8,
    tone: "Drama",
    actorCount: 2,
    pages: 22,
    authorName: "Angelina Joly",
    authorGender: "Female",
    authorEthnicity: "--",
    authorRegion: "New York",
  },
  {
    id: 8,
    title: "Fiends",
    rating: 9.6,
    tone: "Drama",
    actorCount: 5,
    pages: 21,
    authorName: "J Lo",
    authorGender: "Female",
    authorEthnicity: "--",
    authorRegion: "Puerto Rico",
  },
  {
    id: 9,
    title: "Back to the future",
    rating: 9.9,
    tone: "Comedy",
    actorCount: 2,
    pages: 31,
    authorName: "Michael Bay",
    authorGender: "Male",
    authorEthnicity: "--",
    authorRegion: "New Mexico",
  },
];
